apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: go-proto-micro-
spec:
  # entrypoint is the name of the template used as the starting point of the workflow
  entrypoint: go-proto-micro
  # the 'ci-example' template accepts an parameter 'revision', with a default of 'master'.
  # this can be overridden via argo CLI (e.g. `argo submit ci.yaml -p revision=0dea2d0`)
  arguments:
    parameters:
    - name: revision
      value: master


  templates:
  - name: go-proto-micro
    inputs:
      parameters:
      - name: revision
    steps:
    - - name: build
        template: build-golang
        arguments:
          parameters:
          - name: revision
            value: "{{inputs.parameters.revision}}"

  - name: build-golang
    inputs:
      parameters:
      - name: revision
      artifacts:
      - name: code
        path: /go/src/github.com/senexi/go-proto-micro
        git:
          repo: https://github.com/senexi/go-proto-micro
          revision: "{{inputs.parameters.revision}}"
    container:
      image: senexi/gobuilder:latest
      command: [sh, -c]
      args: ["
        cd /go/src/github.com/senexi/go-proto-micro &&
        git status &&
        chmod +x scripts/* &&
        make generate &&
        go get &&
        make build &&
        mv bin/go-proto-micro /tmp &&
        docker build -t senexi/go-proto-micro:latest .
        "]
      volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: dockersock
          mountPath: "/var/run/docker.sock"
    volumes:
      - name: tmp
        persistentVolumeClaim:
          claimName: argo-pv-claim
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
    outputs:
      artifacts:
      - name: binary
        path: /tmp/go-proto-micro